version: '2.1'

networks:
  servers:

services:

  balancer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DOCKER_BUILDPLATFORM=linux/amd64
    command: "lb"
    networks:
      - servers
    ports:
      - "8090:8090"

  server1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DOCKER_BUILDPLATFORM=linux/amd64
    networks:
      - servers
    ports:
      - "8080:8080"

  server2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DOCKER_BUILDPLATFORM=linux/amd64
    networks:
      - servers
    ports:
      - "8081:8080"

  server3:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DOCKER_BUILDPLATFORM=linux/amd64
    networks:
      - servers
    ports:
      - "8082:8080"
